Update combined - minor and patch (#51)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [org.keycloak:keycloak-services](http://keycloak.org)
([source](https://redirect.github.com/keycloak/keycloak)) | `26.4.1` ->
`26.4.2` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.keycloak:keycloak-services/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.keycloak:keycloak-services/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.keycloak:keycloak-services/26.4.1/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.keycloak:keycloak-services/26.4.1/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [org.keycloak:keycloak-server-spi-private](http://keycloak.org)
([source](https://redirect.github.com/keycloak/keycloak)) | `26.4.1` ->
`26.4.2` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.keycloak:keycloak-server-spi-private/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.keycloak:keycloak-server-spi-private/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.keycloak:keycloak-server-spi-private/26.4.1/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.keycloak:keycloak-server-spi-private/26.4.1/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [org.keycloak:keycloak-server-spi](http://keycloak.org)
([source](https://redirect.github.com/keycloak/keycloak)) | `26.4.1` ->
`26.4.2` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.keycloak:keycloak-server-spi/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.keycloak:keycloak-server-spi/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.keycloak:keycloak-server-spi/26.4.1/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.keycloak:keycloak-server-spi/26.4.1/26.4.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [org.jetbrains.kotlin:kotlin-maven-plugin](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | `2.2.20` ->
`2.2.21` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.jetbrains.kotlin:kotlin-maven-plugin/2.2.21?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.jetbrains.kotlin:kotlin-maven-plugin/2.2.21?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.jetbrains.kotlin:kotlin-maven-plugin/2.2.20/2.2.21?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.jetbrains.kotlin:kotlin-maven-plugin/2.2.20/2.2.21?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [org.jetbrains.kotlin:kotlin-stdlib](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | `2.2.20` ->
`2.2.21` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.jetbrains.kotlin:kotlin-stdlib/2.2.21?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.jetbrains.kotlin:kotlin-stdlib/2.2.21?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.jetbrains.kotlin:kotlin-stdlib/2.2.20/2.2.21?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.jetbrains.kotlin:kotlin-stdlib/2.2.20/2.2.21?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>keycloak/keycloak (org.keycloak:keycloak-services)</summary>

###
[`v26.4.2`](https://redirect.github.com/keycloak/keycloak/releases/tag/26.4.2)

[Compare
Source](https://redirect.github.com/keycloak/keycloak/compare/26.4.1...26.4.2)

<div>

<h2>Upgrading</h2>
<p>Before upgrading refer to <a
href="https://www.keycloak.org/docs/latest/upgrading/#migration-changes">the
migration guide</a> for a complete list of changes.</p>

<h2>All resolved issues</h2>

<h3>Enhancements</h3>
<ul>
<li><a
href="https://redirect.github.com/keycloak/keycloak/issues/42991">#&#8203;42991</a>
Final review and update for UPDATE_EMAIL documentation
<code>docs</code></li>
<li><a
href="https://redirect.github.com/keycloak/keycloak/issues/43351">#&#8203;43351</a>
Make pending email verification attribute removable by admin
<code>user-profile</code></li>
<li><a
href="https://redirect.github.com/keycloak/keycloak/issues/43650">#&#8203;43650</a>
SPIFFE should support OIDC JWK endpoint </li>
</ul>

<h3>Bugs</h3>
<ul>
<li><a
href="https://redirect.github.com/keycloak/keycloak/issues/26374">#&#8203;26374</a>
Workflow failure: Quarkus IT -
FipsDistTest#testUnsupportedHttpsPkcs12KeyStoreInStrictMode
<code>ci</code></li>
<li><a
href="https://redirect.github.com/keycloak/keycloak/issues/30939">#&#8203;30939</a>
Vulnerability in brute force detection settings
<code>authentication</code></li>
<li><a
href="https://redirect.github.com/keycloak/keycloak/issues/43022">#&#8203;43022</a>
Incorrect Basic Auth encoding for OIDC IDentity Provider when Client ID
contains colon <code>identity-brokering</code></li>
<li><a
href="https://redirect.github.com/keycloak/keycloak/issues/43191">#&#8203;43191</a>
Upgrade guide for 26.4.0 should mention new minimal PostgreSQL server
version 13 requirement <code>docs</code></li>
<li><a
href="https://redirect.github.com/keycloak/keycloak/issues/43244">#&#8203;43244</a>
UI crash on admin `/users/add-user` since 26.4.0
<code>admin/ui</code></li>
<li><a
href="https://redirect.github.com/keycloak/keycloak/issues/43544">#&#8203;43544</a>
Intra-document links not rendered in downstream <code>docs</code></li>
<li><a
href="https://redirect.github.com/keycloak/keycloak/issues/43561">#&#8203;43561</a>
Server does not shutdown gracefully when started with --optimized
<code>core</code></li>
</ul>

</div>

</details>

<details>
<summary>JetBrains/kotlin
(org.jetbrains.kotlin:kotlin-maven-plugin)</summary>

###
[`v2.2.21`](https://redirect.github.com/JetBrains/kotlin/releases/tag/v2.2.21):
Kotlin 2.2.21

[Compare
Source](https://redirect.github.com/JetBrains/kotlin/compare/v2.2.20...v2.2.21)

#### Changelog

##### Backend. Wasm

- [`KT-81372`](https://youtrack.jetbrains.com/issue/KT-81372) K/Wasm:
JsException: Exception was thrown while running JavaScript code on
Safari 18.2/18.3
- [`KT-80018`](https://youtrack.jetbrains.com/issue/KT-80018) K/Wasm:
exceptions don't work properly in JavaScriptCore (vm inside Safari,
WebKit)

##### Compiler

- [`KT-81191`](https://youtrack.jetbrains.com/issue/KT-81191) K2: "null
cannot be cast to non-null type ConeTypeParameterLookupTag" with invalid
code
- [`KT-80936`](https://youtrack.jetbrains.com/issue/KT-80936)
NON\_PUBLIC\_CALL\_FROM\_PUBLIC\_INLINE : `@PublishedApi` doesn't work
for fun interfaces

##### JavaScript

- [`KT-79926`](https://youtrack.jetbrains.com/issue/KT-79926) Wrong
export of interfaces with companions with ES Modules
- [`KT-81424`](https://youtrack.jetbrains.com/issue/KT-81424) Kotlin/JS:
Cannot Get / in a simple running application
- [`KT-80873`](https://youtrack.jetbrains.com/issue/KT-80873) KJS:
Stdlib requires ES2020-compatible JS engine due to BigInt type literal

##### Native

- [`KT-79384`](https://youtrack.jetbrains.com/issue/KT-79384) K/N:
Application Not Responding: Thread Deadlock

##### Tools. Gradle

- [`KT-79047`](https://youtrack.jetbrains.com/issue/KT-79047) Gradle
compileKotlin fails with configuration cache
- [`KT-81148`](https://youtrack.jetbrains.com/issue/KT-81148) Publishing
helpers in KGP are incompatible with Isolated Projects
- [`KT-80950`](https://youtrack.jetbrains.com/issue/KT-80950) KGP breaks
configuration cache when signing plugin with GnuPG is applied

##### Tools. Gradle. Multiplatform

- [`KT-61127`](https://youtrack.jetbrains.com/issue/KT-61127) Remove
scoped resolvable and intransitive DependenciesMetadata configurations
used in the pre-IdeMultiplatformImport IDE import
- [`KT-81249`](https://youtrack.jetbrains.com/issue/KT-81249) Kotlin
2.2.20 broke KMP implementation of Parcelize

##### Tools. Gradle. Native

- [`KT-81510`](https://youtrack.jetbrains.com/issue/KT-81510)
`commonizeCInterop` exception with 'kotlinNativeBundleConfiguration' not
found
- [`KT-81134`](https://youtrack.jetbrains.com/issue/KT-81134) Native:
Gradle configuration failure likely related to Klibs cross-compilation
- [`KT-77732`](https://youtrack.jetbrains.com/issue/KT-77732)
`commonizeCInterop` failed with "Unresolved classifier:
platform/posix/size\_t"
- [`KT-80675`](https://youtrack.jetbrains.com/issue/KT-80675) Commonized
cinterops between "test" compilations produce an import failure

##### Tools. Maven

- [`KT-81218`](https://youtrack.jetbrains.com/issue/KT-81218) Kotlin
Maven Plugin 2.2.20: Java classes not resolved with enabled incremental
compilation without daemon

##### Tools. Wasm

- [`KT-80582`](https://youtrack.jetbrains.com/issue/KT-80582) Multiple
reloads when using webpack dev server after 2.2.20-Beta2

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 12:30am and before 6:30am every
weekday,every weekend" in timezone Europe/Oslo, Automerge - At any time
(no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/dsb-norge/keycloak-friendly-captcha).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4xNTYuMSIsInVwZGF0ZWRJblZlciI6IjQxLjE1Ni4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJwci1jcmVhdGVkLWJ5LXJlbm92YXRlIl19-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>